## Numpy

Mirar los videos que están en la plataforma de Acámica y tratar de resolver los siguientes ejercicios y preguntas. La documentación de Numpy es muy buena, recomendamos ir familiarizándose con ella.

### Repaso

Importamos la librería

In [1]:
import numpy as np

A partir de una lista podemos crear un arreglo de numpy

In [2]:
lista = [0,1,2,3,4,5]
arreglo = np.array(lista)
print(lista)
print(arreglo)

[0, 1, 2, 3, 4, 5]
[0 1 2 3 4 5]


Pero para algunos casos numpy tiene funciones que crean listas más rápidamente.

In [3]:
arreglo = np.arange(6)
print(arreglo)

[0 1 2 3 4 5]


Algunas cosas que no se podían hacer con las listas ahora sí se pueden:

1. Sumarle un mismo elemento a toda la lista

In [4]:
lista + 1

TypeError: can only concatenate list (not "int") to list

In [5]:
arreglo + 2

array([2, 3, 4, 5, 6, 7])

2. Elevar al cuadrado todos los elementos de una lista

In [6]:
lista**2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [7]:
arreglo**2

array([ 0,  1,  4,  9, 16, 25], dtype=int32)

**Ejercicio 1**: Responder las siguientes preguntas:
* ¿Qué operaciones se pueden hacer tanto en un arreglo de Numpy como en una lista? Dar un ejemplo en una celda.
* ¿Qué operaciones se pueden hacer en un arreglo de Numpy pero NO en una lista? Explorar algunas opciones y dar un ejemplo en una celda.
* ¿Cuál es la diferencia entre un arreglo de forma -shape- (n,), (n,1) y (1,n)? Pueden crear arreglos para intentar responder esa pregunta.

In [ ]:
COMPLETAR

In [ ]:
COMPLETAR

In [ ]:
COMPLETAR

**Ejercicio 2**:
* Escribir un arreglo con números enteros del 0 al 9. Pista: arange
* Escribir un arreglo con 100 números equiespaciados del 0 al 9. Pista: linspace

In [ ]:
COMPLETAR

In [ ]:
COMPLETAR

**Ejercicio 3**:
* Escribir un arreglo con números enteros del 10 al 100 y seleccionar aquellos que son menores que 50.

In [ ]:
a = np.arange(0,4)
'''Pista'''
print(a<2)
mask = [True, False, True, False]
print(a[mask])

In [ ]:
COMPLETAR

**Ejercicio 4**:
* Crear un arreglo de ceros de `shape` (5,10).
* Reemplazar la segunda y cuarta fila con unos
* Reemplazar la tercera y octava columna con dos (2).

In [ ]:
COMPLETAR

In [ ]:
COMPLETAR

In [ ]:
COMPLETAR

**Ejercicio $\infty$**:
Hacer todos los ejercicios que puedan del siguiente link https://www.machinelearningplus.com/python/101-numpy-exercises-python/

O de https://github.com/rougier/numpy-100